import { createClient } from "@supabase/supabase-js";
const admin = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
const SUPER_EMAIL = "ab.benezzine@gmail.com";
const SUPER_PWD = "Benezzine2025";
const SUPER_ID = "adb686ff-85fe-497d-919d-57149a338891";
const DUP_AUTH_ID = "24d9e0f6-642f-4354-9788-3707fabd4a8f";
const HIJACK_ASSOC_ID = "b4746d66-8e7c-4a09-be0b-3d9e402ebfb5";

const e1 = await admin.from("associations").delete().eq("id", HIJACK_ASSOC_ID);
console.log("del assoc:", e1.error ?? "ok");
await admin.from("user_roles").delete().eq("user_id", DUP_AUTH_ID);
await admin.from("profiles").delete().eq("id", DUP_AUTH_ID);
const e2 = await admin.auth.admin.deleteUser(DUP_AUTH_ID);
console.log("del dup user:", e2.error ?? "ok");
const e3 = await admin.auth.admin.updateUserById(SUPER_ID, { password: SUPER_PWD, email: SUPER_EMAIL, email_confirm: true });
console.log("reset pwd:", e3.error ?? "ok");
await admin.from("profiles").upsert({ id: SUPER_ID, email: SUPER_EMAIL, nom: "Super Administrateur", assoc_id: null });
await admin.from("user_roles").delete().eq("user_id", SUPER_ID);
const e4 = await admin.from("user_roles").insert({ user_id: SUPER_ID, role: "superadmin" });
console.log("role:", e4.error ?? "ok");
