/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAssociationsRouteImport } from './routes/app.associations'
import { Route as AppActionsRouteImport } from './routes/app.actions'
import { Route as AppActionsIdRouteImport } from './routes/app.actions.$id'
import { Route as AppActionsIdEvaluationRouteImport } from './routes/app.actions.$id.evaluation'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAssociationsRoute = AppAssociationsRouteImport.update({
  id: '/associations',
  path: '/associations',
  getParentRoute: () => AppRoute,
} as any)
const AppActionsRoute = AppActionsRouteImport.update({
  id: '/actions',
  path: '/actions',
  getParentRoute: () => AppRoute,
} as any)
const AppActionsIdRoute = AppActionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppActionsRoute,
} as any)
const AppActionsIdEvaluationRoute = AppActionsIdEvaluationRouteImport.update({
  id: '/evaluation',
  path: '/evaluation',
  getParentRoute: () => AppActionsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/actions': typeof AppActionsRouteWithChildren
  '/app/associations': typeof AppAssociationsRoute
  '/app/': typeof AppIndexRoute
  '/app/actions/$id': typeof AppActionsIdRouteWithChildren
  '/app/actions/$id/evaluation': typeof AppActionsIdEvaluationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/actions': typeof AppActionsRouteWithChildren
  '/app/associations': typeof AppAssociationsRoute
  '/app': typeof AppIndexRoute
  '/app/actions/$id': typeof AppActionsIdRouteWithChildren
  '/app/actions/$id/evaluation': typeof AppActionsIdEvaluationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/app/actions': typeof AppActionsRouteWithChildren
  '/app/associations': typeof AppAssociationsRoute
  '/app/': typeof AppIndexRoute
  '/app/actions/$id': typeof AppActionsIdRouteWithChildren
  '/app/actions/$id/evaluation': typeof AppActionsIdEvaluationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app/actions'
    | '/app/associations'
    | '/app/'
    | '/app/actions/$id'
    | '/app/actions/$id/evaluation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app/actions'
    | '/app/associations'
    | '/app'
    | '/app/actions/$id'
    | '/app/actions/$id/evaluation'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/app/actions'
    | '/app/associations'
    | '/app/'
    | '/app/actions/$id'
    | '/app/actions/$id/evaluation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/associations': {
      id: '/app/associations'
      path: '/associations'
      fullPath: '/app/associations'
      preLoaderRoute: typeof AppAssociationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/actions': {
      id: '/app/actions'
      path: '/actions'
      fullPath: '/app/actions'
      preLoaderRoute: typeof AppActionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/actions/$id': {
      id: '/app/actions/$id'
      path: '/$id'
      fullPath: '/app/actions/$id'
      preLoaderRoute: typeof AppActionsIdRouteImport
      parentRoute: typeof AppActionsRoute
    }
    '/app/actions/$id/evaluation': {
      id: '/app/actions/$id/evaluation'
      path: '/evaluation'
      fullPath: '/app/actions/$id/evaluation'
      preLoaderRoute: typeof AppActionsIdEvaluationRouteImport
      parentRoute: typeof AppActionsIdRoute
    }
  }
}

interface AppActionsIdRouteChildren {
  AppActionsIdEvaluationRoute: typeof AppActionsIdEvaluationRoute
}

const AppActionsIdRouteChildren: AppActionsIdRouteChildren = {
  AppActionsIdEvaluationRoute: AppActionsIdEvaluationRoute,
}

const AppActionsIdRouteWithChildren = AppActionsIdRoute._addFileChildren(
  AppActionsIdRouteChildren,
)

interface AppActionsRouteChildren {
  AppActionsIdRoute: typeof AppActionsIdRouteWithChildren
}

const AppActionsRouteChildren: AppActionsRouteChildren = {
  AppActionsIdRoute: AppActionsIdRouteWithChildren,
}

const AppActionsRouteWithChildren = AppActionsRoute._addFileChildren(
  AppActionsRouteChildren,
)

interface AppRouteChildren {
  AppActionsRoute: typeof AppActionsRouteWithChildren
  AppAssociationsRoute: typeof AppAssociationsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActionsRoute: AppActionsRouteWithChildren,
  AppAssociationsRoute: AppAssociationsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
